### ISSUE TITLE
SWA

### ISSUE THREAD

**Issue by Lg955** [DLLXW/data-science-competition#17]
使用SWA的时候，我想每间隔5个epoch保存一个权重，opt.swap_swa_sgd()和opt.bn_update(train_loader, model)要放在什么位置？pytorch文档里面说放在训练完成之后，这样的话就只能是最后一个epoch的权重保存了SWA，其他的没有啊

**Comment by DLLXW** [comment]
> 使用SWA的时候，我想每间隔5个epoch保存一个权重，opt.swap_swa_sgd()和opt.bn_update(train_loader, model)要放在什么位置？pytorch文档里面说放在训练完成之后，这样的话就只能是最后一个epoch的权重保存了SWA，其他的没有啊

建议离线进行swa，这样更容易work

**Comment by Lg955** [comment]
先按照正常方法训练、保存权重，等全部训练完，使用其中几个权重加权取平均？

> > 使用SWA的时候，我想每间隔5个epoch保存一个权重，opt.swap_swa_sgd()和opt.bn_update(train_loader, model)要放在什么位置？pytorch文档里面说放在训练完成之后，这样的话就只能是最后一个epoch的权重保存了SWA，其他的没有啊
> 
> 建议离线进行swa，这样更容易work
