### ISSUE TITLE
线上线下分数不同问题

### ISSUE THREAD

**Issue by alacic** [DLLXW/data-science-competition#19]
全球人工智能技术创新大赛【赛道一】线上线下分数的差别可能不来自于计算方式；可能是举办方故意按比例选了更难分辨的样本集，不知道大佬对这种情况可有解题思路呀？

![image](https://user-images.githubusercontent.com/31500048/110076019-c0fd0e00-7dbe-11eb-844a-6f6753590862.png)

**Comment by DLLXW** [comment]
> 全球人工智能技术创新大赛【赛道一】线上线下分数的差别可能不来自于计算方式；可能是举办方故意按比例选了更难分辨的样本集，不知道大佬对这种情况可有解题思路呀？
> 
> ![image](https://user-images.githubusercontent.com/31500048/110076019-c0fd0e00-7dbe-11eb-844a-6f6753590862.png)

我代码里面的logloss计算有误，需要再除以一个类别数，不过这样算下来线上线下还是差了很多。究其原因，就是你说的分布不一致的问题。这种情况，你只能靠线上验证了，但是不建议这样搞，如果b榜分布又变化了肯定血崩。。我也没有很好的解决思路

**Comment by alacic** [comment]
soga，谢谢讲解
