### ISSUE TITLE
关于环境

### ISSUE THREAD

**Issue by xLuge** [DLLXW/data-science-competition#2]
感谢开源，能介绍一下基础环境吗  如torch版本

**Comment by DLLXW** [comment]
你问的哪一个比赛?我在每一个比赛的对应目录里面基本都有写.没有特殊说明的版本都不那么重要.

**Comment by xLuge** [comment]
垃圾分类比赛。 我的结果89.89 未修改任何参数，远达不到92.

**Comment by DLLXW** [comment]
> 垃圾分类比赛。 我的结果89.89 未修改任何参数，远达不到92.
那是你自己配置和训练的问题， 而且和你选取的epoch有关,线下验证集参考价值不大(因为我只分了0.1)，建议将训练尺度适当调大，92是使用288的尺度训练的模型.这个毕竟只是baseline，我去掉了很多的trick，留下的改进空间还很大
