### ISSUE TITLE
wechat 2021

### ISSUE THREAD

**Issue by xnuohz** [DLLXW/data-science-competition#22]
按照readme运行部分运行前三个命令，使用lgb生成的submit文件与test_a.csv的(userid, feedid)不一致

**Comment by DLLXW** [comment]
一个是那个comm. py里面那两需要取消注释噢。还有一个是可能lgb提交那块有点bug，因为lgb那块代码是当天修改过的还没来得及验证，我后面修复下。


 
---Original---
From: ***@***.***&gt;
Date: 2021/6/1 03:31:14
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [DLLXW/data-science-competition] wechat 2021 (#22)




 
按照readme运行部分运行前三个命令，使用lgb生成的submit文件与test_a.csv的(userid, feedid)不一致

**Comment by DLLXW** [comment]
deepFM的是没有问题的


 
---Original---
From: ***@***.***&gt;
Date: 2021/6/1 03:31:14
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [DLLXW/data-science-competition] wechat 2021 (#22)




 
按照readme运行部分运行前三个命令，使用lgb生成的submit文件与test_a.csv的(userid, feedid)不一致

**Comment by DLLXW** [comment]
这编码需要注释掉，因为被重新编码了，所以导致提交的id对不上，这个是我的失误，忘了改了


 
---Original---
From: ***@***.***&gt;
Date: 2021/6/1 03:31:14
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [DLLXW/data-science-competition] wechat 2021 (#22)




 
按照readme运行部分运行前三个命令，使用lgb生成的submit文件与test_a.csv的(userid, feedid)不一致

**Comment by xnuohz** [comment]
[process_data](https://github.com/DLLXW/data-science-competition/blob/4ce8928ebe6a461152ee7fb5c513e733d56913c7/else/wechat2021/lgb.py#L52)这个函数应该可以删掉了，deepfm的环境太老了，我跑不起来hhh
