### ISSUE TITLE
天气情况图像分类

### ISSUE THREAD

**Issue by shining-love** [DLLXW/data-science-competition#29]
由于数据集中存在大量的干扰背景，真正对最终分类结果影响较大的区域占比较小，因此团队在原始的swsl_resnext101_32x8d的基础上添加注意力机制模块CBAM，让模型能够更有效的学到关键区域。

请问这个加入CBAM的代码在哪里?没有找到。

**Comment by DLLXW** [comment]
> 
CBAM这部分代码没上传

**Comment by DLLXW** [comment]
> 由于数据集中存在大量的干扰背景，真正对最终分类结果影响较大的区域占比较小，因此团队在原始的swsl_resnext101_32x8d的基础上添加注意力机制模块CBAM，让模型能够更有效的学到关键区域。
> 
> 请问这个加入CBAM的代码在哪里?没有找到。

感兴趣可以自己找一下CBAM怎么即插即用到现有的任何网络里面，比较方便
