### ISSUE TITLE
广东工业智造创新大赛切图保存子图问题

### ISSUE THREAD

**Issue by WangRongsheng** [DLLXW/data-science-competition#31]
[https://github.com/DLLXW/data-science-competition/tree/main/%E5%A4%A9%E6%B1%A0/2021%E5%B9%BF%E4%B8%9C%E5%B7%A5%E4%B8%9A%E6%99%BA%E9%80%A0%E5%88%9B%E6%96%B0%E5%A4%A7%E8%B5%9B](https://github.com/DLLXW/data-science-competition/tree/main/%E5%A4%A9%E6%B1%A0/2021%E5%B9%BF%E4%B8%9C%E5%B7%A5%E4%B8%9A%E6%99%BA%E9%80%A0%E5%88%9B%E6%96%B0%E5%A4%A7%E8%B5%9B)

你好，请问2021广东工业智造创新大赛**切图** 操作以后只保存了xml标注，没有保存分割的图像，请问怎么修改，我修改了几次，没有成功~谢谢

**Comment by DLLXW** [comment]
> https://github.com/DLLXW/data-science-competition/tree/main/%E5%A4%A9%E6%B1%A0/2021%E5%B9%BF%E4%B8%9C%E5%B7%A5%E4%B8%9A%E6%99%BA%E9%80%A0%E5%88%9B%E6%96%B0%E5%A4%A7%E8%B5%9B
> 
> 你好，请问2021广东工业智造创新大赛**切图** 操作以后只保存了xml标注，没有保存分割的图像，请问怎么修改，我修改了几次，没有成功~谢谢

我想可能是路径的问题，你可以把保存的路径print出来看看是否是期望的路径，是否有这个目录。这代码很多人用过，是没问题的，你仔细debug一下就知道了，不是什么大问题
