### ISSUE TITLE
Asking for help with the access to the dataset

### ISSUE THREAD

**Issue by allmancy13** [DLLXW/data-science-competition#34]
Hello!
I found your repository, and it means you are taking part in the contest and deal with the data.
I had unfortunately lost my copy of training data (pet_biometric_challenge_2022.zip) - and now the access expired. Could i please ask you to share your copy, please? I will really appreciate any help. I know I am late with the contest - but I am really interested in working on the data.
Please excuse me for asking, but I feel really desperate about that - and still found no way to contact the organizers directly.
Arianna

**Comment by DLLXW** [comment]
> Hello! I found your repository, and it means you are taking part in the contest and deal with the data. I had unfortunately lost my copy of training data (pet_biometric_challenge_2022.zip) - and now the access expired. Could i please ask you to share your copy, please? I will really appreciate any help. I know I am late with the contest - but I am really interested in working on the data. Please excuse me for asking, but I feel really desperate about that - and still found no way to contact the organizers directly. Arianna

Sorry, I have deleted the dataset after the competition!You can try join the official DingTalk group on the competition website page! Also, I've updated my solution in this contest,you can check the code in https://github.com/DLLXW/data-science-competition/tree/main/tianchi/2022CVPR-petBiometricChalenge

**Comment by allmancy13** [comment]
Thank you for your answer (and the link to the code)! Could you please explain how to access the official chat?.. I spent some time trying to do so, but gailed to find anything looking like a chat. Thank you really very much.
Arianna

**Comment by DLLXW** [comment]
> Thank you for your answer (and the link to the code)! Could you please explain how to access the official chat?.. I spent some time trying to do so, but gailed to find anything looking like a chat. Thank you really very much. Arianna

The dataset is avaliable in this [link](https://pan.baidu.com/s/1yYNJFuyrJy8kn5TVA5_Okw) [password:d0kc]
