### ISSUE TITLE
切图步长

### ISSUE THREAD

**Issue by world2025** [DLLXW/data-science-competition#35]
![image](https://user-images.githubusercontent.com/41476675/186348794-9f12d6a2-45d2-48a3-81a7-075212074d43.png)
您好，我有个困惑，就是切图大小为640，那步长是不是也是640而不是512，虽然感觉是小儿科问题

**Comment by DLLXW** [comment]
> ![image](https://user-images.githubusercontent.com/41476675/186348794-9f12d6a2-45d2-48a3-81a7-075212074d43.png) 您好，我有个困惑，就是切图大小为640，那步长是不是也是640而不是512，虽然感觉是小儿科问题

设置512就会有一定的overlap，如果设置640则一点overlap都没有

**Comment by world2025** [comment]
@DLLXW 哦哦，好的，切图大小也是跟数据集自身大小有关是吧，这个是通过overlap去调控切图大小的吗

**Comment by world2025** [comment]
![image](https://user-images.githubusercontent.com/41476675/187108896-9fafa200-888e-4edf-a454-63eb49fa99a6.png)
@DLLXW 还有就是这一块，我理解应该也是512？
