### ISSUE TITLE
关于切图的错误

### ISSUE THREAD

**Issue by zhousiqi1999** [DLLXW/data-science-competition#7]
0%|                                                                                         | 0/5388 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\Tianchi\yolov5_material\yolov5-master\make_slice_voc.py", line 223, in <module>
    slice_im(image_path, ann_path, out_name, outdir, sliceHeight=1024, sliceWidth=1024)
  File "D:\Tianchi\yolov5_material\yolov5-master\make_slice_voc.py", line 194, in slice_im
    make_slice_voc(outpath,exiset_obj_list,sliceHeight,sliceWidth)
  File "D:\Tianchi\yolov5_material\yolov5-master\make_slice_voc.py", line 85, in make_slice_voc
    with codecs.open(os.path.join(slice_voc_dir,  name[:-4] + '.xml'), 'w', 'utf-8') as xml:
  File "D:\Anaconda3\envs\yolov5\lib\codecs.py", line 904, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 22] Invalid argument: './slice/annotations\\JPEGImages\\0|819_3276_1024_1024_0_8192_6000.xml'
请按任意键继续. . .
![屏幕截图 2021-01-20 170445](https://user-images.githubusercontent.com/61898875/105152088-ba357700-5b41-11eb-938e-4771711386fb.jpg)

**Comment by DLLXW** [comment]
> 0%| | 0/5388 [00:00<?, ?it/s]
> Traceback (most recent call last):
> File "D:\Tianchi\yolov5_material\yolov5-master\make_slice_voc.py", line 223, in
> slice_im(image_path, ann_path, out_name, outdir, sliceHeight=1024, sliceWidth=1024)
> File "D:\Tianchi\yolov5_material\yolov5-master\make_slice_voc.py", line 194, in slice_im
> make_slice_voc(outpath,exiset_obj_list,sliceHeight,sliceWidth)
> File "D:\Tianchi\yolov5_material\yolov5-master\make_slice_voc.py", line 85, in make_slice_voc
> with codecs.open(os.path.join(slice_voc_dir, name[:-4] + '.xml'), 'w', 'utf-8') as xml:
> File "D:\Anaconda3\envs\yolov5\lib\codecs.py", line 904, in open
> file = builtins.open(filename, mode, buffering)
> OSError: [Errno 22] Invalid argument: './slice/annotations\JPEGImages\0|819_3276_1024_1024_0_8192_6000.xml'
> 请按任意键继续. . .
> ![屏幕截图 2021-01-20 170445](https://user-images.githubusercontent.com/61898875/105152088-ba357700-5b41-11eb-938e-4771711386fb.jpg)

这种路径错误的bug很容易解决的啊，你看这个都提示你了，annotation下为什么会有JPEGImages呢，./slice/annotations是切出来的小块图的xml保存路径啊，./slice/JPEGImages是切出来的图片保存路径。你看你是不是混着写了，这个自己自信看一下代码就好了

**Comment by hxk55668** [comment]
![image](https://github.com/user-attachments/assets/5b75ba19-3821-471d-99d1-83cb411c6d97)
大佬，为啥我也是这个问题，路径没问题啊

**Comment by hxk55668** [comment]
![image](https://github.com/user-attachments/assets/d82616ae-2ea4-4e5f-af8a-71e57d401f09)
大佬，为啥我也是这个问题，路径没问题
